add maximum post limit

diff --git a/template_postfileb64 b/template_postfileb64
--- a/template_postfileb64
+++ b/template_postfileb64
@@ -14,6 +14,14 @@ fi
 
 source ../params.sh
 
+if [[ "$MAX_POSTS" -gt 0 && $(ls [0-9]* 2>/dev/null | wc -l) -ge $MAX_POSTS ]]
+then
+	printf "3Post failed.	fake	(NULL)	0\r\n"
+	printf "iPost limit reached ($MAX_POSTS)	fake	(NULL)	0\r\n"
+	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
+	exit 1
+fi
+
 if [ ! $MAX_UPLOAD -gt 0 ]
 then
 	printf "3Uploads are disabled	fake	(NULL)	0\r\n"
