Rewrite to plain sh

diff --git a/template_postlink b/template_postlink
--- a/template_postlink
+++ b/template_postlink
@@ -1,27 +1,26 @@
-#!/bin/bash
+#!/bin/sh
 
-cd "${0%/*}"
-
-if [ ! -e "../params.sh" ]
-then
-	exit 1
-fi
-
-source ../params.sh
-
-if [[ "$MAX_POSTS" -gt 0 && $(ls [0-9]* 2>/dev/null | wc -l) -ge $MAX_POSTS ]]
-then
-	printf "3Post failed.	fake	(NULL)	0\r\n"
-	printf "iPost limit reached ($MAX_POSTS)	fake	(NULL)	0\r\n"
-	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
-	exit 1
-fi
+cd $(dirname "$0")
 
 id=$(basename $(pwd))
 
+if [ ! -e ../params.sh ]
+then
+	exit 1
+fi
+
+. ../params.sh
+
+if [ "$MAX_POSTS" -gt 0 ] && [ $(ls [0-9]* 2>/dev/null | wc -l) -ge "$MAX_POSTS" ]
+then
+	pherror "Post failed: Post limit reached ($MAX_POSTS)"
+	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
+	exit 1
+fi
+
 stamp=$(date +%s)
 
-if [[ -e ../posts ]]
+if [ -e ../posts ]
 then
 	no=$(cat ../posts)
 else
@@ -33,99 +32,99 @@ post="$stamp"_"$no"
 
 url=$(echo "$@" | cut -c1-$MAX_POSTLEN)
 
-if [[ "$url" != *"://"* ]]
+if ! echo "$url" | grep -q '://'
 then
-	printf "3Invalid URL: $url	fake	(NULL)	0\r\n"
-	printf "iYou must include the protocol (http://, gopher://, etc.)	fake	(NULL)	0\r\n"
-	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
+	pherror "Invalid URL: $url"
+	phinfo 'You must include the protocol (http://, gopher://, etc.)'
+	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
 	exit 1
 fi
 
-proto="${url%://*}"
-uri="${url##*://}"
+proto=$(echo "$url" | sed -r 's/^([^:]+):\/\/.+$/\1/')
+uri=$(echo "$url" | sed -r 's/^[^:]+:\/\/(.+)$/\1/')
 
-if [[ "$proto" == *" "* ]]
+if echo "$proto" | grep -q ' '
 then
-	display=$(echo "$proto" | rev | cut -f 2- -d ' ' | rev | cut -c1-70)
+	dis=$(echo "$proto" | rev | cut -f 2- -d ' ' | rev | cut -c1-70)
 	proto=$(echo "$proto" | rev | cut -f 1 -d ' ' | rev)
 else
-	display=$(echo "$url" | cut -c1-70)
+	dis=$(echo "$url" | cut -c1-70)
 fi
 
 # quotes
-targetno=$(echo "$display" | sed -r 's/>>([0-9]+) ?.*/\1/')
-if  [[ "$display" == ">>"* && "$targetno" -gt 0 ]]
+targetno=$(echo "$dis" | sed -r 's/>>([0-9]+) ?.*/\1/')
+if echo "$dis" | grep -q '^>>.*'
 then
-	target=$(ls ../[0-9]*_*/[0-9]*_$targetno 2>/dev/null | head -n 1)
-	target="${target#../}"
+	target=$(find .. -name "[0-9]*_$targetno" | head -n 1)
 
-	if [[ ! "$target" ]]
+	if [ ! -e "$target" ]
 	then
-		printf "3Post #$targetno does not exist!	fake	(NULL)	0\r\n"
-		printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
+		pherror "Post #$targetno does not exist."
+		phitem 1 'Return to thread' "$CHAN_ROOT/$id"
 		exit 1
 	fi
 
-	thread="${target%/*}"
+	thread=$(echo "$target" | cut -d / -f 2)
 
-	if [[ "$thread" == "$id" ]]
+	if [ "$thread" = "$id" ]
 	then
 		echo "#$targetno said:" >> $post
 	else
-		echo "1$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
+		echo "1#$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
 	fi
 
 	saveifs="$IFS"
 	IFS=''
-	while read -r line
+	cat $target | while read -r line
 	do
-		if echo "$line" | grep -q -v "	"
+		if echo "$line" | grep -v -q "	"
 		then
-			while read -r fmtline
+			echo "$line" | fmt -66 -s | fold -w 66 | while read -r fmtline
 			do
 				echo "  >$fmtline" >> $post
-			done < <(echo "$line" | fmt -66 -s | fold -w 66)
+			done
 		else
 			kind=$(echo "$line" | head -c 1)
 			rest=$(echo "$line" | tail -c +2)
 			echo "$kind  >$rest" >> $post
 		fi
-	done < ../$target
+	done
 	IFS="$saveifs"
 
-	display=$(echo "$display" | sed -r 's/>>[0-9]+ ?(.*)/\1/')
+	dis=$(echo "$dis" | sed -r 's/>>[0-9]+ ?(.*)/\1/' | sed 's/	/    /g')
+fi
 
-	if [[ ! "$display" ]]
-	then
-		display="$proto://$uri"
-	fi
+if [ "$dis" = '' ]
+then
+	dis="$proto://$uri"
 fi
 
 case $proto in
-	"")		printf "3Invalid URL: $url	fake	(NULL)	0\r\n"
-			printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
+	"")		pherror "Invalid URL: $url"
+			phitem 1 'Return to thread'
 			exit 1;;
-	"gopher")	comment=$(../guri "$proto://$uri" "$display");;
-	*)		comment="h$display	URL:$proto://$uri	$SERVER_HOST	$SERVER_PORT"
+	"gopher")	comment=$(../guri "$proto://$uri" "$dis");;
+	*)		comment="h$dis	URL:$proto://$uri	$SERVER_HOST	$SERVER_PORT"
 esac
 
-if [[ ! "$comment" ]]
+if [ ! "$comment" ]
 then
-	printf "3Post failed.	fake	(NULL)	0\r\n"
-	printf "iInvalid URL:	fake	(NULL)	0\r\n"
-	printf "i$url	fake	(NULL)	0\r\n"
-else
-	echo "$comment" >> $post
-
-	if [ -e $post ]
-	then
-		printf "iPost successfuly!	fake	(NULL)	0\r\n"
-
-		echo $no > ../posts
-		../updatepostcache $id $post >> postcache
-	else
-		printf "3Could not post.	fake	(NULL)	0\r\n"
-	fi
+	pherror "Post failed: Invalid URL: $url"
+	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
+	exit 1
 fi
 
-printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
+echo "$comment" >> $post
+
+if [ -e $post ]
+then
+	printf "iPost successfuly!	fake	(NULL)	0\r\n"
+
+	echo $no > ../posts
+	../updatepostcache $id $post >> postcache
+else
+	printf "3Could not post.	fake	(NULL)	0\r\n"
+	pherror 'Could not post'
+fi
+
+phitem 1 'Return to thread' "$CHAN_ROOT/$id"
